{"uuid": "f0bead1f-32d9-4d45-844b-ab94aec6ea74", "children": ["c8f35794-cc83-46b6-b76d-d19a08a10523", "d7514524-bbca-49bc-848a-cfd476643ea6", "15aa6922-921d-4e9f-b5bf-aba16e2b53b3", "81ec48f3-fd44-4787-88b3-600f9a7c2551", "bf2c2298-299d-45f9-9691-15bfad68e095", "0f1b709f-e26f-4f30-af47-6f39ae655fb6", "d10e1020-9bdc-4ee8-a9e4-add94a556593", "fd14284f-c372-4592-81da-32373356733f", "80effa99-35c7-4dee-9004-aa95f4e8263e"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=112.0.5615.138)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00FADCE3+50899]\n\t(No symbol) [0x00F3E111]\n\t(No symbol) [0x00E45588]\n\t(No symbol) [0x00E2D333]\n\t(No symbol) [0x00E8F4DB]\n\t(No symbol) [0x00E9DB33]\n\t(No symbol) [0x00E8B6F6]\n\t(No symbol) [0x00E67708]\n\t(No symbol) [0x00E6886D]\n\tGetHandleVerifier [0x01213EAE+2566302]\n\tGetHandleVerifier [0x012492B1+2784417]\n\tGetHandleVerifier [0x0124327C+2759788]\n\tGetHandleVerifier [0x01045740+672048]\n\t(No symbol) [0x00F48872]\n\t(No symbol) [0x00F441C8]\n\t(No symbol) [0x00F442AB]\n\t(No symbol) [0x00F371B7]\n\tBaseThreadInitThunk [0x769D7D49+25]\n\tRtlInitializeExceptionChain [0x7795B74B+107]\n\tRtlClearBits [0x7795B6CF+191]\n\n", "trace": "  File \"C:\\Users\\alexh\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\alexh\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\alexh\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\alexh\\PycharmProjects\\eventvendor\\mainfile\\conftest.py\", line 29, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\alexh\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 592, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\alexh\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\alexh\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1683963884910, "stop": 1683963974604}], "start": 1683963884910, "stop": 1683963976013}